export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const ADD_ROOM = 'ADD_ROOM';
export const FETCH_ROOMS = 'FETCH_ROOMS';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
